### ISSUE TITLE
Validation of Sigma Rules Does Not Handle Specific Invalid Cases Properly

### ISSUE THREAD

**Issue by tribeiro42** [jopohl/sigma-rust#19]
The library currently fails to properly handle certain invalid Sigma rule scenarios. 
This leads to cases where invalid rules are either accepted or not reported as errors.

```
title: "Invalid Condition Example"
logsource:
  category: process_creation
detection:
  selection:
    CommandLine|contains: "example"
  condition: "undefined_field"
```

```
title: "Missing Logsource Example"
detection:
  selection:
    CommandLine|contains: "example"
  condition: "selection"
```

```
title: "Advanced Condition Example"
logsource:
  category: process_creation
detection:
  selection1:
    CommandLine|contains: "curl"
  selection2:
    CommandLine|contains: "wget"
  condition: "selection1 AND (selection2 OR undefined_field)"
```

Code for check : 

```
use sigma_rust::{rule_from_yaml, check_rule, Rule};
use std::fs;

fn main() {
    let invalid_rule = r#"
    title: "Invalid Condition Example"
    logsource:
      category: process_creation
    detection:
      selection:
        CommandLine|contains: "example"
      condition: "undefined_field"
    "#;

    let rule = rule_from_yaml(invalid_rule);
    match rule {
        Ok(_) => println!("The invalid rule was incorrectly accepted."),
        Err(e) => println!("Validation failed as expected: {}", e),
    }
}
```

Its something on your roadmap or its out of scope ?
Thx by advence
