### ISSUE TITLE
Add support for * and ? wildcards

### ISSUE THREAD

**Issue by theflakes** [jopohl/sigma-rust#8]
Hello, and thank you for this crate.

I'm playing with it and can't get the below to work. I am seeing the rule loaded correctly as well as the log. The problem seems to be the substring search. I can match the full string.

rule
```
id: e781ae02-0d7b-4c3a-b1e3-d3b6b24f6c5b
title: Example Sigma Rule
description: Detects example log entries
status: experimental
author: Brian Kellogg
tags:
  - test
logsource:
  product: windows
  service: sysmon
detection:
  error:
    norm_keys.messsage: '*error*'
  condition: error
falsepositives:
  - NA
level: high
```

Log
```
{"count":5,"enabled":"true","lvl":"error","msg":"This is an error message","norm_keys":{"enabled":true,"level":"error","message":"This is an error message"},"sigma_rules":[],"tags":["example","test"]}
```

Sigma match function
```
fn apply_sigma_rules(log_entry: &Value, rules: &Vec<Rule>) -> Vec<Value> {
    let mut matched_rules = Vec::new();
    let event = event_from_json(&log_entry.to_string()).unwrap();

    for rule in rules {
        if rule.is_match(&event) {
            matched_rules.push(Value::String(rule.title.clone()));
        } else {
            println!("Rule did not match!");
        }
    }

    matched_rules
}
```

**Comment by jopohl** [comment]
Hi! To clarify, you expect the condition `norm_keys.messsage: '*error*'` to match `... "norm_keys":{"enabled":true,"level":"error","message":"This is an error message"} ...`? On a side note, in  `norm_keys.messsage` the word "message" is written with three "s". 

I think you rather want the `contains` modifier in this case because otherwise the engine performs an exact string matching for `*error*`, i.e., your message would need to be something like `"This is an *error* message"`.

To sum up, I suggest to rewrite your rule as follows.

```yaml
id: e781ae02-0d7b-4c3a-b1e3-d3b6b24f6c5b
title: Example Sigma Rule
description: Detects example log entries
status: experimental
author: Brian Kellogg
tags:
  - test
logsource:
  product: windows
  service: sysmon
detection:
  error:
    norm_keys.message|contains: 'error'
  condition: error
falsepositives:
  - NA
level: high
```

Does this work for you?
